const languagesData = {
    "c": [
        { url: "https://mix-n-fix-compiler.onrender.com/?code=MQSwdgxgNgrgJgUwAQB4QHsDOAXATggQwFsA+AKFElkVQDcEJt1dzLp5kUwYiFcQIrcOxooc-MAHNyZaAUyYkAZWwcw2JAG8yABxgAjKAIBcZJOaQ44x4+PCSkYYggDcZi1Zv1GzNOpJIkrgEiJhu7uZw6AZQyBAEUBAwUATYCACC9MGSCAAUAJRIEOhgOFoRFuYgAGZIuUEhCJgAdAhEOtgAngWF+Kq4YEgADM1DbpWVUTHImDxIALyW2NbGBBBJRMmpeQ2hzfoIkuAFADSBwXsIYHCnw6P54xPmfTADlnMA9OeNLZggAF55B4VAC+ZBB4XAGiIBGOhW0lShRWi6jOs30ACsGNgAMIo7CPcyeYzFGAaFAoJAAIgAouo+I4eAdcEh0LUcGpsIoCNd3pjsYodAyOYh1MZqYSkDU6gBCXLEiDgJAkAKk9TKgLorGMPEwdT5XoIfqDACM4UqxO8TFwKBUnNVKQUuHQ6CIuTV2GBFuWNkVYGaIEkYGYQJcSA+X2ghBZ4D0Gn0MGq1T4ZAq1WYdSRIAWwzD2cpHrDAGoiyB4RVvStSeTKbT6SynLwkOmWSKrhoqahKdmi0gTV3qeKqZLKzYctgjGA8grwGc5E6XUQANogAC6zUbCGBFYs88wztdK-XuyazXwmD49HlBm1uPxXqeSyr0Rr1LpaRZnYpfNvuvV387E9MCHEcLBbTN1QxHMxiQKDKS1bE-wJJASwxctHwmJET1Ap4Z0GFVvkQHCJj3A9lzXZogOaPRMAACwAfX0NYAGt6guLdiLBDC8IDIMQwKSUwQqBUXwHKkAB0wAAWhkpAAAU+BbGFIGQAAlBAdGYDQZKkyThzTDN3RKMoCDJdAADIlk5JBxVIxd0MfESyQHNt1A3ZwdwwyoAKQAAfJBMj4AgciHTyvPMb9XOwZp4kSLY0kC7IgTC8LIp9YwrjgKBBNTSoXjeMZwTIIA&lang=cpp", title: "C Program 1: Hello World" },
        { url: "#", title: "C Program 2: Variables & Data Types" },
        { url: "#", title: "C Program 3: If-Else Condition" },
        { url: "#", title: "C Program 4: Loops (For, While)" },
        { url: "#", title: "C Program 5: Arrays" },
        { url: "#", title: "C Program 6: Functions" },
        { url: "#", title: "C Program 7: Pointers" },
        { url: "#", title: "C Program 8: Structures" },
        { url: "#", title: "C Program 9: Unions" },
        { url: "#", title: "C Program 10: File Handling" },
        { url: "#", title: "C Program 11: Dynamic Memory" },
        { url: "#", title: "C Program 12: Preprocessors" },
        { url: "#", title: "C Program 13: Recursion" },
        { url: "#", title: "C Program 14: String Handling" },
        { url: "#", title: "C Program 15: Bitwise Operators" },
        { url: "#", title: "C Program 16: Sorting Algorithms" },
        { url: "#", title: "C Program 17: Searching Algorithms" },
        { url: "#", title: "C Program 18: Stack Implementation" },
        { url: "#", title: "C Program 19: Queue Implementation" },
        { url: "#", title: "C Program 20: Linked List" }
    ],
    "cpp": [
        { url: "https://mix-n-fix-compiler.onrender.com/?code=MQSwdgxgNgrgJgUwAQB4QHsDOAXATggQwFsA+AKFElkVQDcEJt1dzLp5kUwYiFcQIrcOxooc-MAHNyZaAUyYkAZWwcw2JAG8yABxgAjKAIBcZJOaQ44x4+PCSkYYggDcZi1Zv1GzNOpJIkrgEiJhu7uZw6AZQyBAEUBAwUATYCACC9MGSCAAUAJRIEOhgOFoRFuYgAGZIuUEhCJgAdAhEOtgAngWF+Kq4YEgADM1DbpWVUTHImDxIALyW2NbGBBBJRMmpeQ2hzfoIkuAFADSBwXsIYHCnw6P54xPmfTADlnMA9OeNLZggAF55B4VAC+ZBB4XAGiIBGOhW0lShRWi6jOs30ACsGNgAMIo7CPcyeYzFGAaFAoJAAIgAouo+I4eAdcEh0LUcGpsIoCNd3pjsYodAyOYh1MZqYSkDU6gBCXLEiDgJAkAKk9TKgLorGMPEwdT5XoIfqDACM4UqxO8TFwKBUnNVKQUuHQ6CIuTV2GBFuWNkVYGaIEkYGYQJcSA+X2ghBZ4D0Gn0MGq1T4ZAq1WYdSRIAWwzD2cpHrDAGoiyB4RVvStSeTKbT6SynLwkOmWSKrhoqahKdmi0gTV3qeKqZLKzYctgjGA8grwGc5E6XUQANogAC6zUbCGBFYs88wztdK-XuyazXwmD49HlBm1uPxXqeSyr0Rr1LpaRZnYpfNvuvV387E9MCHEcLBbTN1QxHMxiQKDKS1bE-wJJASwxctHwmJET1Ap4Z0GFVvkQHCJj3A9lzXZogOaPRMAACwAfX0NYAGt6guLdiLBDC8IDIMQwKSUwQqBUXwHKkAB0wAAWhkpAAAU+BbGFIGQAAlBAdGYDQZKkyThzTDN3RKMoCDJdAADIlk5JBxVIxd0MfESyQHNt1A3ZwdwwyoAKQAAfJBMj4AgciHTyvPMb9XOwZp4kSLY0kC7IgTC8LIp9YwrjgKBBNTSoXjeMZwTIIA&lang=cpp", title: "C++ Program 1: Hello World" },
        { url: "#", title: "C++ Program 2: Input/Output" },
        { url: "#", title: "C++ Program 3: Classes & Objects" },
        { url: "#", title: "C++ Program 4: Constructors" },
        { url: "#", title: "C++ Program 5: Inheritance" },
        { url: "#", title: "C++ Program 6: Polymorphism" },
        { url: "#", title: "C++ Program 7: Encapsulation" },
        { url: "#", title: "C++ Program 8: Abstraction" },
        { url: "#", title: "C++ Program 9: Exception Handling" },
        { url: "#", title: "C++ Program 10: Templates" },
        { url: "#", title: "C++ Program 11: STL Vectors" },
        { url: "#", title: "C++ Program 12: STL Maps" },
        { url: "#", title: "C++ Program 13: Operator Overloading" },
        { url: "#", title: "C++ Program 14: Friend Functions" },
        { url: "#", title: "C++ Program 15: Lambda Expressions" },
        { url: "#", title: "C++ Program 16: File Streams" },
        { url: "#", title: "C++ Program 17: Multi-threading" },
        { url: "#", title: "C++ Program 18: Smart Pointers" },
        { url: "#", title: "C++ Program 19: Move Semantics" },
        { url: "#", title: "C++ Program 20: Design Patterns" }
    ],
    "python": [
        { url: "#", title: "Python Program 1: Hello World" },
        { url: "#", title: "Python Program 2: Variables" },
        { url: "#", title: "Python Program 3: Lists & Tuples" },
        { url: "#", title: "Python Program 4: Dictionaries" },
        { url: "#", title: "Python Program 5: If-Else" },
        { url: "#", title: "Python Program 6: Loops" },
        { url: "#", title: "Python Program 7: Functions" },
        { url: "#", title: "Python Program 8: Modules" },
        { url: "#", title: "Python Program 9: File Handling" },
        { url: "#", title: "Python Program 10: Exception Handling" },
        { url: "#", title: "Python Program 11: Classes" },
        { url: "#", title: "Python Program 12: Inheritance" },
        { url: "#", title: "Python Program 13: Decorators" },
        { url: "#", title: "Python Program 14: Generators" },
        { url: "#", title: "Python Program 15: Lambda Functions" },
        { url: "#", title: "Python Program 16: RegEx" },
        { url: "#", title: "Python Program 17: Requests Lib" },
        { url: "#", title: "Python Program 18: Pandas Basics" },
        { url: "#", title: "Python Program 19: NumPy Basics" },
        { url: "#", title: "Python Program 20: Flask Intro" }
    ],
    "java": [
        { url: "#", title: "Java Program 1: Hello World" },
        { url: "#", title: "Java Program 2: Variables" },
        { url: "#", title: "Java Program 3: Operators" },
        { url: "#", title: "Java Program 4: Loop Control" },
        { url: "#", title: "Java Program 5: Arrays" },
        { url: "#", title: "Java Program 6: Methods" },
        { url: "#", title: "Java Program 7: OOPS Concepts" },
        { url: "#", title: "Java Program 8: Inheritance" },
        { url: "#", title: "Java Program 9: Interfaces" },
        { url: "#", title: "Java Program 10: Packages" },
        { url: "#", title: "Java Program 11: Exception Handling" },
        { url: "#", title: "Java Program 12: Multithreading" },
        { url: "#", title: "Java Program 13: Collections" },
        { url: "#", title: "Java Program 14: File I/O" },
        { url: "#", title: "Java Program 15: JavaFX Basics" },
        { url: "#", title: "Java Program 16: Streams API" },
        { url: "#", title: "Java Program 17: Lambda Expressions" },
        { url: "#", title: "Java Program 18: Networking" },
        { url: "#", title: "Java Program 19: JDBC" },
        { url: "#", title: "Java Program 20: Spring Intro" }
    ],
    "js": [
        { url: "#", title: "JS Program 1: Hello World" },
        { url: "#", title: "JS Program 2: Variables (var, let, const)" },
        { url: "#", title: "JS Program 3: Functions" },
        { url: "#", title: "JS Program 4: Arrow Functions" },
        { url: "#", title: "JS Program 5: Arrays & Methods" },
        { url: "#", title: "JS Program 6: Objects" },
        { url: "#", title: "JS Program 7: DOM Manipulation" },
        { url: "#", title: "JS Program 8: Events" },
        { url: "#", title: "JS Program 9: Async/Await" },
        { url: "#", title: "JS Program 10: Promises" },
        { url: "#", title: "JS Program 11: Fetch API" },
        { url: "#", title: "JS Program 12: ES6 Modules" },
        { url: "#", title: "JS Program 13: LocalStorage" },
        { url: "#", title: "JS Program 14: Classes" },
        { url: "#", title: "JS Program 15: Destructuring" },
        { url: "#", title: "JS Program 16: Spread/Rest Operator" },
        { url: "#", title: "JS Program 17: Closures" },
        { url: "#", title: "JS Program 18: Callbacks" },
        { url: "#", title: "JS Program 19: Error Handling" },
        { url: "#", title: "JS Program 20: Web Workers" }
    ]
};

export default languagesData;
